# ETL Pipeline Execution: Spotify Data Processing

This notebook demonstrates the complete data pipeline:
1. **Raw Stage**: Load CSV files and convert to Parquet
2. **Processed Stage**: Clean, validate, and deduplicate data
3. **Analytics Stage**: Denormalize and select relevant features for analysis
4. **Database Sync**: Load data to Supabase database (PostgreSQL)

## Setup

In [1]:
import sys
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

import pandas as pd
import pyarrow.parquet as pq

# Add project to path
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Load environment variables (force override if already set in kernel)
load_dotenv(project_root / '.env', override=True)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import pipeline stages
from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage
from soeSpotify.database import DatabaseLoader
from soeSpotify import config

logger.info('Pipeline modules imported successfully')

2026-06-27 13:59:04,764 - __main__ - INFO - Pipeline modules imported successfully

## Stage 1: Raw Data Processing

In this stage we load the CSV files and convert them to Parquet for efficient storage and faster access.

In [2]:
logger.info('Starting Raw Stage...')
start_time = datetime.now()

raw = RawStage()
raw.run()

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Raw Stage completed in {elapsed:.1f} seconds')

2026-06-27 13:59:06,806 - __main__ - INFO - Starting Raw Stage...
2026-06-27 13:59:06,809 - soeSpotify.stages.raw - INFO - Raw parquet directory ready: /workspaces/soe-spotify/data/raw/parquet
2026-06-27 13:59:06,812 - soeSpotify.stages.raw - INFO - ============================================================
2026-06-27 13:59:06,812 - soeSpotify.stages.raw - INFO - RAW STAGE: Loading CSV files → Raw Parquet
2026-06-27 13:59:06,814 - soeSpotify.stages.raw - INFO - ============================================================
2026-06-27 13:59:06,814 - soeSpotify.stages.raw - INFO - Loading tracks from /workspaces/soe-spotify/data/raw/SpotGenTrack/Data Sources/spotify_tracks.csv
2026-06-27 13:59:25,144 - soeSpotify.stages.raw - INFO - Loaded 101939 tracks
2026-06-27 13:59:25,145 - soeSpotify.stages.raw - INFO - Saving to /workspaces/soe-spotify/data/raw/parquet/raw_tracks.parquet
2026-06-27 13:59:25,882 - soeSpotify.stages.raw - INFO - Saved 101939 tracks to raw stage
2026-06-27 13:59:25,883 - soeSpotify.stages.raw - INFO - Loading artists from /workspaces/soe-spotify/data/raw/SpotGenTrack/Data Sources/spotify_artists.csv
2026-06-27 13:59:26,482 - soeSpotify.stages.raw - INFO - Loaded 56129 artists
2026-06-27 13:59:26,483 - soeSpotify.stages.raw - INFO - Saving to /workspaces/soe-spotify/data/raw/parquet/raw_artists.parquet
2026-06-27 13:59:26,533 - soeSpotify.stages.raw - INFO - Saved 56129 artists to raw stage
2026-06-27 13:59:26,533 - soeSpotify.stages.raw - INFO - Loading albums from /workspaces/soe-spotify/data/raw/SpotGenTrack/Data Sources/spotify_albums.csv
2026-06-27 13:59:33,280 - soeSpotify.stages.raw - INFO - Loaded 75511 albums
2026-06-27 13:59:33,280 - soeSpotify.stages.raw - INFO - Saving to /workspaces/soe-spotify/data/raw/parquet/raw_albums.parquet
2026-06-27 13:59:33,469 - soeSpotify.stages.raw - INFO - Saved 75511 albums to raw stage
2026-06-27 13:59:33,470 - soeSpotify.stages.raw - INFO - Loading audio features from /workspaces/soe-spotify/data/raw/SpotGenTrack/Features Extracted/low_level_audio_features.csv
2026-06-27 13:59:59,086 - soeSpotify.stages.raw - INFO - Loaded 101909 audio feature records
2026-06-27 13:59:59,086 - soeSpotify.stages.raw - INFO - Saving to /workspaces/soe-spotify/data/raw/parquet/raw_audio_features.parquet
2026-06-27 14:00:01,070 - soeSpotify.stages.raw - INFO - Saved 101909 audio features to raw stage
2026-06-27 14:00:01,074 - soeSpotify.stages.raw - INFO - Loading lyrics features from /workspaces/soe-spotify/data/raw/SpotGenTrack/Features Extracted/lyrics_features.csv
2026-06-27 14:00:02,679 - soeSpotify.stages.raw - INFO - Loaded 94954 lyrics feature records
2026-06-27 14:00:02,680 - soeSpotify.stages.raw - INFO - Saving to /workspaces/soe-spotify/data/raw/parquet/raw_lyrics_features.parquet
2026-06-27 14:00:02,876 - soeSpotify.stages.raw - INFO - Saved 94954 lyrics features to raw stage
2026-06-27 14:00:02,879 - soeSpotify.stages.raw - INFO - Raw stage completed successfully
2026-06-27 14:00:02,907 - __main__ - INFO - Raw Stage completed in 56.1 seconds

In [3]:
# Verify raw parquet files were created
raw_files = [
    ('Tracks', config.RAW_TRACKS),
    ('Artists', config.RAW_ARTISTS),
    ('Albums', config.RAW_ALBUMS),
    ('Audio Features', config.RAW_AUDIO_FEATURES),
    ('Lyrics Features', config.RAW_LYRICS_FEATURES),
]

for name, path in raw_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 32 columns
✓ Artists: 56129 rows, 9 columns
✓ Albums: 75511 rows, 16 columns
✓ Audio Features: 101909 rows, 209 columns
✓ Lyrics Features: 94954 rows, 8 columns

## Stage 2: Processed Data

In this stage we clean and validates the raw Spotify datasets. We removed invalid and duplicate records, standardizes important columns, combines audio and lyrics features, and saved the cleaned results as processed Parquet files for the analytics stage.

In [4]:
logger.info('Starting Processed Stage...')
start_time = datetime.now()

# Load raw parquet files
df_raw_tracks = pd.read_parquet(config.RAW_TRACKS)
df_raw_artists = pd.read_parquet(config.RAW_ARTISTS)
df_raw_albums = pd.read_parquet(config.RAW_ALBUMS)
df_raw_audio = pd.read_parquet(config.RAW_AUDIO_FEATURES)
df_raw_lyrics = pd.read_parquet(config.RAW_LYRICS_FEATURES)

processed = ProcessedStage()
processed.run(
    raw_tracks=df_raw_tracks,
    raw_artists=df_raw_artists,
    raw_albums=df_raw_albums,
    raw_audio=df_raw_audio,
    raw_lyrics=df_raw_lyrics,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Processed Stage completed in {elapsed:.1f} seconds')

2026-06-27 14:00:17,025 - __main__ - INFO - Starting Processed Stage...
2026-06-27 14:00:18,134 - soeSpotify.stages.processed - INFO - Processed stage directory ready: /workspaces/soe-spotify/data/processed
2026-06-27 14:00:18,135 - soeSpotify.stages.processed - INFO - ============================================================
2026-06-27 14:00:18,138 - soeSpotify.stages.processed - INFO - PROCESSED STAGE: Cleaning & Validating Data
2026-06-27 14:00:18,139 - soeSpotify.stages.processed - INFO - ============================================================
2026-06-27 14:00:18,141 - soeSpotify.stages.processed - INFO - Processing artists...
2026-06-27 14:00:18,262 - soeSpotify.stages.processed - INFO - Removed null artist_ids, 56129 artists remaining
2026-06-27 14:00:18,292 - soeSpotify.stages.processed - INFO - Removed duplicates, 56129 unique artists
2026-06-27 14:00:18,332 - soeSpotify.stages.processed - INFO - Saving 56129 artists
2026-06-27 14:00:18,415 - soeSpotify.stages.processed - INFO - Processing albums...
2026-06-27 14:00:18,425 - soeSpotify.stages.processed - INFO - Removed null album_ids, 75511 albums remaining
2026-06-27 14:00:18,446 - soeSpotify.stages.processed - INFO - Removed duplicates, 75511 unique albums
2026-06-27 14:00:18,450 - soeSpotify.stages.processed - INFO - Saving 75511 albums
2026-06-27 14:00:18,533 - soeSpotify.stages.processed - INFO - Processing tracks...
2026-06-27 14:00:18,544 - soeSpotify.stages.processed - INFO - Removed null track_ids, 101939 tracks remaining
2026-06-27 14:00:18,561 - soeSpotify.stages.processed - INFO - Removed duplicates, 101939 unique tracks
2026-06-27 14:00:18,573 - soeSpotify.stages.processed - INFO - Saving 101939 tracks
2026-06-27 14:00:18,868 - soeSpotify.stages.processed - INFO - Processing track features...
2026-06-27 14:00:19,338 - soeSpotify.stages.processed - INFO - Combined features for 101909 tracks
2026-06-27 14:00:19,339 - soeSpotify.stages.processed - INFO - Saving 101909 track features
2026-06-27 14:00:21,309 - soeSpotify.stages.processed - INFO - Processed stage completed successfully
2026-06-27 14:00:21,318 - __main__ - INFO - Processed Stage completed in 4.3 seconds

0       -1.00
1        0.45
2        0.59
3        0.49
4        0.47
         ...
94949    0.60
94950    0.40
94951    0.64
94952    0.60
94953    0.65
Name: vocabulary_wealth, Length: 94954, dtype: float64

In [5]:
# Free memory
import gc
del df_raw_tracks, df_raw_artists, df_raw_albums, df_raw_audio, df_raw_lyrics
gc.collect()

0

In [6]:
# Verify processed parquet files
processed_files = [
    ('Tracks', config.PROCESSED_TRACKS),
    ('Artists', config.PROCESSED_ARTISTS),
    ('Albums', config.PROCESSED_ALBUMS),
    ('Track Features', config.PROCESSED_TRACK_FEATURES),
    ('Lyrics Features', config.PROCESSED_TRACK_FEATURES)
]

for name, path in processed_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 26 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 75511 rows, 8 columns
✓ Track Features: 101909 rows, 214 columns
✓ Lyrics Features: 101909 rows, 214 columns

## Stage 3: Analytics Data

In this stage we transformed the cleaned processed Spotify data into final tables. We then mdenormalized the tables and saved all final outputs as Parquet files for reporting and database synchronization.

In [7]:
logger.info('Starting Analytics Stage...')
start_time = datetime.now()

# Load processed parquet files
df_processed_tracks = pd.read_parquet(config.PROCESSED_TRACKS)
df_processed_artists = pd.read_parquet(config.PROCESSED_ARTISTS)
df_processed_albums = pd.read_parquet(config.PROCESSED_ALBUMS)
df_processed_features = pd.read_parquet(config.PROCESSED_TRACK_FEATURES)

analytics = AnalyticsStage()
analytics.run(
    tracks=df_processed_tracks,
    artists=df_processed_artists,
    albums=df_processed_albums,
    features=df_processed_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Analytics Stage completed in {elapsed:.1f} seconds')

2026-06-27 14:00:33,929 - __main__ - INFO - Starting Analytics Stage...
2026-06-27 14:00:34,627 - soeSpotify.stages.analytics - INFO - Analytics stage directory ready: /workspaces/soe-spotify/data/analytics
2026-06-27 14:00:34,629 - soeSpotify.stages.analytics - INFO - ============================================================
2026-06-27 14:00:34,631 - soeSpotify.stages.analytics - INFO - ANALYTICS STAGE: Feature Engineering & Denormalization
2026-06-27 14:00:34,632 - soeSpotify.stages.analytics - INFO - ============================================================
2026-06-27 14:00:34,633 - soeSpotify.stages.analytics - INFO - Building analytics artists table...
2026-06-27 14:00:34,640 - soeSpotify.stages.analytics - INFO - Saving 56129 analytics artists
2026-06-27 14:00:34,688 - soeSpotify.stages.analytics - INFO - Building analytics albums table...
2026-06-27 14:00:35,091 - soeSpotify.stages.analytics - INFO - Filtered albums: 74991/75511 reference valid artists
2026-06-27 14:00:35,133 - soeSpotify.stages.analytics - INFO - Saving 74991 analytics albums
2026-06-27 14:00:35,207 - soeSpotify.stages.analytics - INFO - Building analytics tracks table...
2026-06-27 14:00:36,418 - soeSpotify.stages.analytics - INFO - Filtered tracks: 101144/101939 have valid references
2026-06-27 14:00:36,794 - soeSpotify.stages.analytics - INFO - Saving 101144 analytics tracks
2026-06-27 14:00:37,044 - soeSpotify.stages.analytics - INFO - Building analytics genres table...
2026-06-27 14:00:40,776 - soeSpotify.stages.analytics - INFO - Created 87202 genre mappings
2026-06-27 14:00:40,784 - soeSpotify.stages.analytics - INFO - Saving 87202 analytics genres
2026-06-27 14:00:40,822 - soeSpotify.stages.analytics - INFO - Building analytics track features table...
2026-06-27 14:00:41,680 - soeSpotify.stages.analytics - INFO - Analytics features: 101144 rows, 19 columns
2026-06-27 14:00:41,680 - soeSpotify.stages.analytics - INFO - Saving 101144 feature records
2026-06-27 14:00:41,780 - soeSpotify.stages.analytics - INFO - Analytics stage completed successfully
2026-06-27 14:00:41,781 - __main__ - INFO - Analytics Stage completed in 7.8 seconds

In [8]:
# Free memory
import gc
del df_processed_tracks, df_processed_artists, df_processed_albums, df_processed_features
gc.collect()

99

In [9]:
# Verify analytics parquet files
analytics_files = [
    ('Tracks', config.ANALYTICS_TRACKS),
    ('Artists', config.ANALYTICS_ARTISTS),
    ('Albums', config.ANALYTICS_ALBUMS),
    ('Genres', config.ANALYTICS_GENRES),
    ('Track Features', config.ANALYTICS_TRACK_FEATURES),
]

for name, path in analytics_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101144 rows, 33 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 74991 rows, 10 columns
✓ Genres: 87202 rows, 3 columns
✓ Track Features: 101144 rows, 19 columns

## Stage 4: Database Sync

Load analytics DataFrames to Supabase (PostgreSQL).

In [10]:
# Load analytics dataframes
logger.info('Loading analytics dataframes...')

df_artists = pd.read_parquet(config.ANALYTICS_ARTISTS)
df_albums = pd.read_parquet(config.ANALYTICS_ALBUMS)
df_tracks = pd.read_parquet(config.ANALYTICS_TRACKS)
df_genres = pd.read_parquet(config.ANALYTICS_GENRES)
df_features = pd.read_parquet(config.ANALYTICS_TRACK_FEATURES)

logger.info(f'Artists: {len(df_artists)} rows')
logger.info(f'Albums: {len(df_albums)} rows')
logger.info(f'Tracks: {len(df_tracks)} rows')
logger.info(f'Genres: {len(df_genres)} rows')
logger.info(f'Features: {len(df_features)} rows')

2026-06-27 14:00:46,822 - __main__ - INFO - Loading analytics dataframes...
2026-06-27 14:00:46,994 - __main__ - INFO - Artists: 56129 rows
2026-06-27 14:00:46,995 - __main__ - INFO - Albums: 74991 rows
2026-06-27 14:00:46,996 - __main__ - INFO - Tracks: 101144 rows
2026-06-27 14:00:46,997 - __main__ - INFO - Genres: 87202 rows
2026-06-27 14:00:46,999 - __main__ - INFO - Features: 101144 rows

In [11]:
# Sync to PostgreSQL
logger.info(f'Database URL: {config.DATABASE_URL}')
start_time = datetime.now()

db = DatabaseLoader(database_url=config.DATABASE_URL)
db.run(
    artists=df_artists,
    albums=df_albums,
    tracks=df_tracks,
    genres=df_genres,
    features=df_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Database sync completed in {elapsed:.1f} seconds')

2026-06-27 14:00:48,793 - __main__ - INFO - Database URL: postgresql://postgres.ebqamnwyqigiprsrjurp:SoeSpotify2026!!@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
2026-06-27 14:00:49,406 - soeSpotify.database - INFO - Database connection established
2026-06-27 14:00:49,408 - soeSpotify.database - INFO - ============================================================
2026-06-27 14:00:49,410 - soeSpotify.database - INFO - DATABASE SYNC: Loading Analytics → PostgreSQL
2026-06-27 14:00:49,411 - soeSpotify.database - INFO - ============================================================
2026-06-27 14:00:49,412 - soeSpotify.database - INFO - Dropping existing tables for schema parity...
2026-06-27 14:00:50,586 - soeSpotify.database - INFO - Tables dropped
2026-06-27 14:00:50,587 - soeSpotify.database - INFO - Creating schema 'home'...
2026-06-27 14:00:50,672 - soeSpotify.database - INFO - Schema 'home' ready
2026-06-27 14:00:50,673 - soeSpotify.database - INFO - Creating tables if missing...
2026-06-27 14:00:50,894 - soeSpotify.database - INFO - Tables checked/created
2026-06-27 14:00:50,895 - soeSpotify.database - INFO - Creating base views...
2026-06-27 14:00:51,076 - soeSpotify.database - INFO - Base views created
2026-06-27 14:00:51,077 - soeSpotify.database - INFO - Creating analysis views...
2026-06-27 14:00:51,347 - soeSpotify.database - INFO - Analysis views created
2026-06-27 14:00:51,348 - soeSpotify.database - INFO - Loading 56129 rows to artists
2026-06-27 14:00:58,707 - soeSpotify.database - INFO - Loaded 56129 rows to artists
2026-06-27 14:00:58,708 - soeSpotify.database - INFO - Loading 74991 rows to albums
2026-06-27 14:01:14,841 - soeSpotify.database - INFO - Loaded 74991 rows to albums
2026-06-27 14:01:14,842 - soeSpotify.database - INFO - Loading 101144 rows to tracks
2026-06-27 14:02:32,238 - soeSpotify.database - INFO - Loaded 101144 rows to tracks
2026-06-27 14:02:32,238 - soeSpotify.database - INFO - Loading 87202 rows to genres
2026-06-27 14:02:40,101 - soeSpotify.database - INFO - Loaded 87202 rows to genres
2026-06-27 14:02:40,102 - soeSpotify.database - INFO - Loading 101144 rows to track_features
2026-06-27 14:03:22,003 - soeSpotify.database - INFO - Loaded 101144 rows to track_features
2026-06-27 14:03:22,004 - soeSpotify.database - INFO - Database sync completed successfully
2026-06-27 14:03:22,004 - __main__ - INFO - Database sync completed in 153.2 seconds

## Verify Database Input

Query the data to verify data was loaded correctly.

In [12]:
from sqlalchemy import create_engine, text

engine = create_engine(config.DATABASE_URL, echo=False, future=True)

# Test queries
queries = [
    ('Total Artists', 'SELECT COUNT(*) as count FROM home.artists'),
    ('Total Tracks', 'SELECT COUNT(*) as count FROM home.tracks'),
    ('Total Albums', 'SELECT COUNT(*) as count FROM home.albums'),
    ('Total Genres', 'SELECT COUNT(*) as count FROM home.genres'),
    ('Total Features', 'SELECT COUNT(*) as count FROM home.track_features'),
]

with engine.connect() as conn:
    for name, query in queries:
        result = conn.execute(text(query)).fetchone()
        print(f'{name}: {result[0]:,}')

Total Artists: 56,129
Total Tracks: 101,144
Total Albums: 74,991
Total Genres: 87,202
Total Features: 101,144

In [13]:
# Show top artists by popularity
with engine.connect() as conn:
    query = text('''
        SELECT artist_name, followers, artist_popularity
        FROM home.v_1_2_artists_popularity
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

     artist_name  followers  artist_popularity
0  Ariana Grande   26309771                100
1          Drake   34680740                 98
2    Post Malone   12150628                 96
3     Juice WRLD    3607186                 95
4   XXXTENTACION   11564320                 95
5          Ozuna   15389549                 95
6         Khalid    5476601                 95
7       Anuel Aa    5103877                 94
8          Queen   14130233                 94
9   Travis Scott    5097861                 94

In [14]:
# Show top tracks by features (high energy, danceability, valence)
with engine.connect() as conn:
    query = text('''
        SELECT 
            track_name,
            artist_name,
            danceability,
            energy,
            valence,
            tempo
        FROM home.v_3_1_track_features_full
        WHERE energy > 0.7 AND danceability > 0.6
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

,track_name,artist_name,danceability,energy,valence,tempo
0,Teeje Week,Jordan Sandhu,0.679,0.770,0.839,161.721
1,El Yeyo,Vicente Garcia,0.838,0.703,0.658,104.982
2,Supa Nova,Green Assassin Dollar,0.642,0.712,0.647,83.897
3,Acabaste con mi vida,Franco Argüelles,0.771,0.789,0.771,84.974
4,Fever,YOSA & TAAR,0.662,0.838,0.496,129.884
5,Cada Dia,Tercer Cielo,0.753,0.786,0.867,92.066
6,We Are What We Are (feat. Billy Bros Orchestra...,Bart & Baker,0.843,0.736,0.660,125.012
7,Acceptable in the 80's,Calvin Harris,0.787,0.808,0.942,127.990
8,A.S.S - Original Mix,Future Class,0.814,0.714,0.252,125.005
9,Chances - Mark Ralph Remix,Backstreet Boys,0.689,0.859,0.490,110.022

In [15]:
# Show artist-album relationships
with engine.connect() as conn:
    query = text('''
        SELECT 
            artist_name,
            album_name,
            release_date,
            total_tracks
        FROM home.v_1_5_artist_albums
        WHERE artist_followers > 1000000
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

,artist_name,album_name,release_date,total_tracks
0,Alicia Keys,If I Ain't Got You EP,2019-02-08,6
1,Ludwig van Beethoven,Beethoven: 6 Bagatelles & Piano Sonatas Nos. 3...,2019-03-01,11
2,Ludwig van Beethoven,Beethoven: Piano Concerto No. 2 & Triple Conce...,2019-03-01,7
3,Frédéric Chopin,Chopin: Concertos Nos. 1 & 2,2019-02-22,7
4,Busta Rhymes,The Coming,1996,13
5,Galantis,Bones (feat. OneRepublic) [Steff da Campo Remix],2019-03-01,2
6,R3HAB,Radio Silence (Sem Vox Remix),2019-02-22,1
7,Blur,The Best Of,2000-10-23,28
8,Lil Pump,Drug Addicts,2018-07-06,1
9,Lil Uzi Vert,Go Off,2017-03-02,1