# ETL Pipeline Execution: Spotify Data Processing

This notebook demonstrates the complete data pipeline:
1. **Raw Stage**: Load CSV files and convert to Parquet
2. **Processed Stage**: Clean, validate, and deduplicate data
3. **Analytics Stage**: Denormalize and engineer features for analysis
4. **Database Sync**: Load to PostgreSQL using migration-based schema creation to preserve PK/FK relations and analytical views.

## Setup

In [1]:
import sys
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

import pandas as pd
import pyarrow.parquet as pq

# Add project to path
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Load environment variables (force override if already set in kernel)
load_dotenv(project_root / '.env', override=True)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import pipeline stages
from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage
from soeSpotify.database import DatabaseLoader
from soeSpotify import config

logger.info('Pipeline modules imported successfully')

2026-05-17 19:31:23,415 - __main__ - INFO - Pipeline modules imported successfully

In [2]:
import importlib
import sys

logger.info('Performing deep module reload to pick up code changes...')

# Remove modules from cache to force reimport
modules_to_reload = [
    'soeSpotify.stages.analytics',
    'soeSpotify.stages.processed', 
    'soeSpotify.stages.raw',
    'soeSpotify.database',
    'soeSpotify.config'
]

for mod in modules_to_reload:
    if mod in sys.modules:
        del sys.modules[mod]

# Now import fresh
from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage
from soeSpotify.database import DatabaseLoader

logger.info('Modules reloaded with latest code changes')

2026-05-17 19:31:23,448 - __main__ - INFO - Performing deep module reload to pick up code changes...
2026-05-17 19:31:23,456 - __main__ - INFO - Modules reloaded with latest code changes

## Stage 1: Raw Data Processing

Load CSV files and convert to Parquet for efficient storage and retrieval.

In [3]:
import shutil

logger.info('Clearing all processed and analytics data to start fresh...')
shutil.rmtree(config.DATA_PROCESSED, ignore_errors=True)
shutil.rmtree(config.DATA_ANALYTICS, ignore_errors=True)
logger.info('Old processed/analytics data cleared')

# Deep reload updated modules
import sys
for mod in ['soeSpotify.stages.processed', 'soeSpotify.stages.analytics', 
            'soeSpotify.stages.raw']:
    if mod in sys.modules:
        del sys.modules[mod]

from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage

logger.info('Updated modules reloaded - ready for fresh pipeline run')

2026-05-17 19:31:23,519 - __main__ - INFO - Clearing all processed and analytics data to start fresh...
2026-05-17 19:31:23,586 - __main__ - INFO - Old processed/analytics data cleared
2026-05-17 19:31:23,596 - __main__ - INFO - Updated modules reloaded - ready for fresh pipeline run

In [4]:
logger.info('Starting Raw Stage...')
start_time = datetime.now()

raw = RawStage()
raw.run()

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Raw Stage completed in {elapsed:.1f} seconds')

2026-05-17 19:31:23,664 - __main__ - INFO - Starting Raw Stage...
2026-05-17 19:31:23,666 - soeSpotify.stages.raw - INFO - Raw parquet directory ready: d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet
2026-05-17 19:31:23,667 - soeSpotify.stages.raw - INFO - ============================================================
2026-05-17 19:31:23,668 - soeSpotify.stages.raw - INFO - RAW STAGE: Loading CSV files → Raw Parquet
2026-05-17 19:31:23,669 - soeSpotify.stages.raw - INFO - ============================================================
2026-05-17 19:31:23,670 - soeSpotify.stages.raw - INFO - Loading tracks from d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_tracks.csv
2026-05-17 19:31:27,227 - soeSpotify.stages.raw - INFO - Loaded 101939 tracks
2026-05-17 19:31:27,228 - soeSpotify.stages.raw - INFO - Saving to d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_tracks.parquet
2026-05-17 19:31:28,312 - soeSpotify.stages.raw - INFO - Saved 101939 tracks to raw stage
2026-05-17 19:31:28,315 - soeSpotify.stages.raw - INFO - Loading artists from d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_artists.csv
2026-05-17 19:31:28,789 - soeSpotify.stages.raw - INFO - Loaded 56129 artists
2026-05-17 19:31:28,791 - soeSpotify.stages.raw - INFO - Saving to d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_artists.parquet
2026-05-17 19:31:28,899 - soeSpotify.stages.raw - INFO - Saved 56129 artists to raw stage
2026-05-17 19:31:28,900 - soeSpotify.stages.raw - INFO - Loading albums from d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_albums.csv
2026-05-17 19:31:30,322 - soeSpotify.stages.raw - INFO - Loaded 75511 albums
2026-05-17 19:31:30,324 - soeSpotify.stages.raw - INFO - Saving to d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_albums.parquet
2026-05-17 19:31:30,553 - soeSpotify.stages.raw - INFO - Saved 75511 albums to raw stage
2026-05-17 19:31:30,556 - soeSpotify.stages.raw - INFO - Loading audio features from d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Features Extracted\low_level_audio_features.csv
2026-05-17 19:31:34,168 - soeSpotify.stages.raw - INFO - Loaded 101909 audio feature records
2026-05-17 19:31:34,169 - soeSpotify.stages.raw - INFO - Saving to d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_audio_features.parquet
2026-05-17 19:31:37,064 - soeSpotify.stages.raw - INFO - Saved 101909 audio features to raw stage
2026-05-17 19:31:37,065 - soeSpotify.stages.raw - INFO - Loading lyrics features from d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Features Extracted\lyrics_features.csv
2026-05-17 19:31:37,258 - soeSpotify.stages.raw - INFO - Loaded 94954 lyrics feature records
2026-05-17 19:31:37,260 - soeSpotify.stages.raw - INFO - Saving to d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_lyrics_features.parquet
2026-05-17 19:31:37,343 - soeSpotify.stages.raw - INFO - Saved 94954 lyrics features to raw stage
2026-05-17 19:31:37,345 - soeSpotify.stages.raw - INFO - Raw stage completed successfully
2026-05-17 19:31:37,383 - __main__ - INFO - Raw Stage completed in 13.7 seconds

In [5]:
# Verify raw parquet files were created
raw_files = [
    ('Tracks', config.RAW_TRACKS),
    ('Artists', config.RAW_ARTISTS),
    ('Albums', config.RAW_ALBUMS),
    ('Audio Features', config.RAW_AUDIO_FEATURES),
    ('Lyrics Features', config.RAW_LYRICS_FEATURES),
]

for name, path in raw_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 32 columns
✓ Artists: 56129 rows, 9 columns
✓ Albums: 75511 rows, 16 columns
✓ Audio Features: 101909 rows, 209 columns
✓ Lyrics Features: 94954 rows, 8 columns

## Stage 2: Processed Data

Clean, validate, and deduplicate data. Combine audio and lyrics features.

In [6]:
logger.info('Starting Processed Stage...')
start_time = datetime.now()

# Load raw parquet files
df_raw_tracks = pd.read_parquet(config.RAW_TRACKS)
df_raw_artists = pd.read_parquet(config.RAW_ARTISTS)
df_raw_albums = pd.read_parquet(config.RAW_ALBUMS)
df_raw_audio = pd.read_parquet(config.RAW_AUDIO_FEATURES)
df_raw_lyrics = pd.read_parquet(config.RAW_LYRICS_FEATURES)

processed = ProcessedStage()
processed.run(
    raw_tracks=df_raw_tracks,
    raw_artists=df_raw_artists,
    raw_albums=df_raw_albums,
    raw_audio=df_raw_audio,
    raw_lyrics=df_raw_lyrics,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Processed Stage completed in {elapsed:.1f} seconds')

2026-05-17 19:31:38,321 - __main__ - INFO - Starting Processed Stage...
2026-05-17 19:31:39,180 - soeSpotify.stages.processed - INFO - Processed stage directory ready: d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\processed
2026-05-17 19:31:39,182 - soeSpotify.stages.processed - INFO - ============================================================
2026-05-17 19:31:39,185 - soeSpotify.stages.processed - INFO - PROCESSED STAGE: Cleaning & Validating Data
2026-05-17 19:31:39,186 - soeSpotify.stages.processed - INFO - ============================================================
2026-05-17 19:31:39,187 - soeSpotify.stages.processed - INFO - Processing artists...
2026-05-17 19:31:39,198 - soeSpotify.stages.processed - INFO - Removed null artist_ids, 56129 artists remaining
2026-05-17 19:31:39,212 - soeSpotify.stages.processed - INFO - Removed duplicates, 56129 unique artists
2026-05-17 19:31:39,217 - soeSpotify.stages.processed - INFO - Saving 56129 artists
2026-05-17 19:31:39,337 - soeSpotify.stages.processed - INFO - Processing albums...
2026-05-17 19:31:39,347 - soeSpotify.stages.processed - INFO - Removed null album_ids, 75511 albums remaining
2026-05-17 19:31:39,364 - soeSpotify.stages.processed - INFO - Removed duplicates, 75511 unique albums
2026-05-17 19:31:39,367 - soeSpotify.stages.processed - INFO - Saving 75511 albums
2026-05-17 19:31:39,527 - soeSpotify.stages.processed - INFO - Processing tracks...
2026-05-17 19:31:39,543 - soeSpotify.stages.processed - INFO - Removed null track_ids, 101939 tracks remaining
2026-05-17 19:31:39,558 - soeSpotify.stages.processed - INFO - Removed duplicates, 101939 unique tracks
2026-05-17 19:31:39,568 - soeSpotify.stages.processed - INFO - Saving 101939 tracks
2026-05-17 19:31:40,076 - soeSpotify.stages.processed - INFO - Processing track features...
2026-05-17 19:31:40,338 - soeSpotify.stages.processed - INFO - Combined features for 101909 tracks
2026-05-17 19:31:40,340 - soeSpotify.stages.processed - INFO - Saving 101909 track features
2026-05-17 19:31:44,208 - soeSpotify.stages.processed - INFO - Processed stage completed successfully
2026-05-17 19:31:44,226 - __main__ - INFO - Processed Stage completed in 5.9 seconds

In [7]:
# Verify processed parquet files
processed_files = [
    ('Tracks', config.PROCESSED_TRACKS),
    ('Artists', config.PROCESSED_ARTISTS),
    ('Albums', config.PROCESSED_ALBUMS),
    ('Track Features', config.PROCESSED_TRACK_FEATURES),
]

for name, path in processed_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 26 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 75511 rows, 8 columns
✓ Track Features: 101909 rows, 214 columns

In [8]:
# DEBUG: Check what's actually in processed features before analytics
df_processed_features = pd.read_parquet(config.PROCESSED_TRACK_FEATURES)
print(f"PROCESSED_TRACK_FEATURES columns ({len(df_processed_features.columns)} total):")
print(df_processed_features.columns.tolist()[:20])  # Show first 20
print(f"\nTotal: {len(df_processed_features.columns)} columns")
print(f"\nChecking for audio features:")
for col in ["acousticness", "danceability", "energy", "tempo"]:
    print(f"  {col}: {'YES' if col in df_processed_features.columns else 'NO'}")

PROCESSED_TRACK_FEATURES columns (214 total):
['Chroma_1', 'Chroma_10', 'Chroma_11', 'Chroma_12', 'Chroma_2', 'Chroma_3', 'Chroma_4', 'Chroma_5', 'Chroma_6', 'Chroma_7', 'Chroma_8', 'Chroma_9', 'MEL_1', 'MEL_10', 'MEL_100', 'MEL_101', 'MEL_102', 'MEL_103', 'MEL_104', 'MEL_105']

Total: 214 columns

Checking for audio features:
  acousticness: NO
  danceability: NO
  energy: NO
  tempo: NO

## Stage 3: Analytics Data

Denormalize and create features for analysis and ML. Join artist/album/track relationships.

In [9]:
logger.info('Starting Analytics Stage...')
start_time = datetime.now()

# Load processed parquet files
df_processed_tracks = pd.read_parquet(config.PROCESSED_TRACKS)
df_processed_artists = pd.read_parquet(config.PROCESSED_ARTISTS)
df_processed_albums = pd.read_parquet(config.PROCESSED_ALBUMS)
df_processed_features = pd.read_parquet(config.PROCESSED_TRACK_FEATURES)

analytics = AnalyticsStage()
analytics.run(
    tracks=df_processed_tracks,
    artists=df_processed_artists,
    albums=df_processed_albums,
    features=df_processed_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Analytics Stage completed in {elapsed:.1f} seconds')

2026-05-17 19:31:45,163 - __main__ - INFO - Starting Analytics Stage...
2026-05-17 19:31:45,606 - soeSpotify.stages.analytics - INFO - Analytics stage directory ready: d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\analytics
2026-05-17 19:31:45,608 - soeSpotify.stages.analytics - INFO - ============================================================
2026-05-17 19:31:45,609 - soeSpotify.stages.analytics - INFO - ANALYTICS STAGE: Feature Engineering & Denormalization
2026-05-17 19:31:45,611 - soeSpotify.stages.analytics - INFO - ============================================================
2026-05-17 19:31:45,613 - soeSpotify.stages.analytics - INFO - Building analytics artists table...
2026-05-17 19:31:45,619 - soeSpotify.stages.analytics - INFO - Saving 56129 analytics artists
2026-05-17 19:31:45,688 - soeSpotify.stages.analytics - INFO - Building analytics albums table...
2026-05-17 19:31:46,151 - soeSpotify.stages.analytics - INFO - Filtered albums: 74991/75511 reference valid artists
2026-05-17 19:31:46,191 - soeSpotify.stages.analytics - INFO - Saving 74991 analytics albums
2026-05-17 19:31:46,329 - soeSpotify.stages.analytics - INFO - Building analytics tracks table...
2026-05-17 19:31:47,687 - soeSpotify.stages.analytics - INFO - Filtered tracks: 101144/101939 have valid references
2026-05-17 19:31:47,974 - soeSpotify.stages.analytics - INFO - Saving 101144 analytics tracks
2026-05-17 19:31:48,360 - soeSpotify.stages.analytics - INFO - Building analytics genres table...
2026-05-17 19:31:52,552 - soeSpotify.stages.analytics - INFO - Created 87202 genre mappings
2026-05-17 19:31:52,559 - soeSpotify.stages.analytics - INFO - Saving 87202 analytics genres
2026-05-17 19:31:52,623 - soeSpotify.stages.analytics - INFO - Building analytics track features table...
2026-05-17 19:31:53,523 - soeSpotify.stages.analytics - INFO - Analytics features: 101144 rows, 19 columns
2026-05-17 19:31:53,525 - soeSpotify.stages.analytics - INFO - Saving 101144 feature records
2026-05-17 19:31:53,657 - soeSpotify.stages.analytics - INFO - Analytics stage completed successfully
2026-05-17 19:31:53,663 - __main__ - INFO - Analytics Stage completed in 8.5 seconds

In [10]:
# Verify analytics parquet files
analytics_files = [
    ('Tracks', config.ANALYTICS_TRACKS),
    ('Artists', config.ANALYTICS_ARTISTS),
    ('Albums', config.ANALYTICS_ALBUMS),
    ('Genres', config.ANALYTICS_GENRES),
    ('Track Features', config.ANALYTICS_TRACK_FEATURES),
]

for name, path in analytics_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101144 rows, 33 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 74991 rows, 10 columns
✓ Genres: 87202 rows, 3 columns
✓ Track Features: 101144 rows, 19 columns

In [11]:
import shutil

logger.info('Clearing old analytics data due to feature extraction fix...')
if config.DATA_ANALYTICS.exists():
    shutil.rmtree(config.DATA_ANALYTICS)
    logger.info('Old analytics directory removed')

logger.info('Re-running Analytics Stage with all audio features...')
start_time = datetime.now()

analytics = AnalyticsStage()
analytics.run(
    tracks=df_processed_tracks,
    artists=df_processed_artists,
    albums=df_processed_albums,
    features=df_processed_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Analytics Stage completed in {elapsed:.1f} seconds')

# Verify updated analytics parquet files (should now have more columns)
analytics_files = [
    ('Tracks', config.ANALYTICS_TRACKS),
    ('Artists', config.ANALYTICS_ARTISTS),
    ('Albums', config.ANALYTICS_ALBUMS),
    ('Genres', config.ANALYTICS_GENRES),
    ('Track Features', config.ANALYTICS_TRACK_FEATURES),
]

print('\nUpdated Analytics Files:')
for name, path in analytics_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

2026-05-17 19:31:54,275 - __main__ - INFO - Clearing old analytics data due to feature extraction fix...
2026-05-17 19:31:54,285 - __main__ - INFO - Old analytics directory removed
2026-05-17 19:31:54,287 - __main__ - INFO - Re-running Analytics Stage with all audio features...
2026-05-17 19:31:54,289 - soeSpotify.stages.analytics - INFO - Analytics stage directory ready: d:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\analytics
2026-05-17 19:31:54,291 - soeSpotify.stages.analytics - INFO - ============================================================
2026-05-17 19:31:54,292 - soeSpotify.stages.analytics - INFO - ANALYTICS STAGE: Feature Engineering & Denormalization
2026-05-17 19:31:54,294 - soeSpotify.stages.analytics - INFO - ============================================================
2026-05-17 19:31:54,296 - soeSpotify.stages.analytics - INFO - Building analytics artists table...
2026-05-17 19:31:54,303 - soeSpotify.stages.analytics - INFO - Saving 56129 analytics artists
2026-05-17 19:31:54,400 - soeSpotify.stages.analytics - INFO - Building analytics albums table...
2026-05-17 19:31:54,954 - soeSpotify.stages.analytics - INFO - Filtered albums: 74991/75511 reference valid artists
2026-05-17 19:31:55,001 - soeSpotify.stages.analytics - INFO - Saving 74991 analytics albums
2026-05-17 19:31:55,127 - soeSpotify.stages.analytics - INFO - Building analytics tracks table...
2026-05-17 19:31:56,655 - soeSpotify.stages.analytics - INFO - Filtered tracks: 101144/101939 have valid references
2026-05-17 19:31:56,901 - soeSpotify.stages.analytics - INFO - Saving 101144 analytics tracks
2026-05-17 19:31:57,274 - soeSpotify.stages.analytics - INFO - Building analytics genres table...
2026-05-17 19:32:01,464 - soeSpotify.stages.analytics - INFO - Created 87202 genre mappings
2026-05-17 19:32:01,473 - soeSpotify.stages.analytics - INFO - Saving 87202 analytics genres
2026-05-17 19:32:01,552 - soeSpotify.stages.analytics - INFO - Building analytics track features table...
2026-05-17 19:32:02,616 - soeSpotify.stages.analytics - INFO - Analytics features: 101144 rows, 19 columns
2026-05-17 19:32:02,619 - soeSpotify.stages.analytics - INFO - Saving 101144 feature records
2026-05-17 19:32:02,812 - soeSpotify.stages.analytics - INFO - Analytics stage completed successfully
2026-05-17 19:32:02,818 - __main__ - INFO - Analytics Stage completed in 8.5 seconds

Updated Analytics Files:
✓ Tracks: 101144 rows, 33 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 74991 rows, 10 columns
✓ Genres: 87202 rows, 3 columns
✓ Track Features: 101144 rows, 19 columns

## Stage 4: Database Sync

Load analytics DataFrames to PostgreSQL. This stage now uses a **migration-aligned workflow**:
1. **Schema Initialization**: Ensures the `home` schema and all tables exist with proper constraints (PKs/FKs).
2. **Data Refresh**: Truncates existing data while keeping table structures intact.
3. **Safe Loading**: Appends fresh data to the pre-defined schema.

In [12]:
# Load analytics dataframes
logger.info('Loading analytics dataframes...')

df_artists = pd.read_parquet(config.ANALYTICS_ARTISTS)
df_albums = pd.read_parquet(config.ANALYTICS_ALBUMS)
df_tracks = pd.read_parquet(config.ANALYTICS_TRACKS)
df_genres = pd.read_parquet(config.ANALYTICS_GENRES)
df_features = pd.read_parquet(config.ANALYTICS_TRACK_FEATURES)

logger.info(f'Artists: {len(df_artists)} rows')
logger.info(f'Albums: {len(df_albums)} rows')
logger.info(f'Tracks: {len(df_tracks)} rows')
logger.info(f'Genres: {len(df_genres)} rows')
logger.info(f'Features: {len(df_features)} rows')

2026-05-17 19:32:03,354 - __main__ - INFO - Loading analytics dataframes...
2026-05-17 19:32:03,639 - __main__ - INFO - Artists: 56129 rows
2026-05-17 19:32:03,640 - __main__ - INFO - Albums: 74991 rows
2026-05-17 19:32:03,641 - __main__ - INFO - Tracks: 101144 rows
2026-05-17 19:32:03,642 - __main__ - INFO - Genres: 87202 rows
2026-05-17 19:32:03,644 - __main__ - INFO - Features: 101144 rows

In [13]:
# Sync to PostgreSQL
logger.info(f'Database URL: {config.DATABASE_URL}')
start_time = datetime.now()

db = DatabaseLoader(database_url=config.DATABASE_URL)
db.run(
    artists=df_artists,
    albums=df_albums,
    tracks=df_tracks,
    genres=df_genres,
    features=df_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Database sync completed in {elapsed:.1f} seconds')

2026-05-17 19:32:03,750 - __main__ - INFO - Database URL: postgresql://postgres:admin@localhost:5432/soe_spotify
2026-05-17 19:32:03,823 - soeSpotify.database - INFO - Database connection established
2026-05-17 19:32:03,825 - soeSpotify.database - INFO - ============================================================
2026-05-17 19:32:03,827 - soeSpotify.database - INFO - DATABASE SYNC: Loading Analytics → PostgreSQL
2026-05-17 19:32:03,828 - soeSpotify.database - INFO - ============================================================
2026-05-17 19:32:03,829 - soeSpotify.database - INFO - Dropping existing tables for schema parity...
2026-05-17 19:32:04,211 - soeSpotify.database - INFO - Tables dropped
2026-05-17 19:32:04,213 - soeSpotify.database - INFO - Creating schema 'home'...
2026-05-17 19:32:04,215 - soeSpotify.database - INFO - Schema 'home' ready
2026-05-17 19:32:04,216 - soeSpotify.database - INFO - Creating tables if missing...
2026-05-17 19:32:04,260 - soeSpotify.database - INFO - Tables checked/created
2026-05-17 19:32:04,261 - soeSpotify.database - INFO - Creating base views...
2026-05-17 19:32:04,269 - soeSpotify.database - INFO - Base views created
2026-05-17 19:32:04,271 - soeSpotify.database - INFO - Creating analysis views...
2026-05-17 19:32:04,288 - soeSpotify.database - INFO - Analysis views created
2026-05-17 19:32:04,289 - soeSpotify.database - INFO - Loading 56129 rows to artists
2026-05-17 19:32:10,483 - soeSpotify.database - INFO - Loaded 56129 rows to artists
2026-05-17 19:32:10,484 - soeSpotify.database - INFO - Loading 74991 rows to albums
2026-05-17 19:32:23,329 - soeSpotify.database - INFO - Loaded 74991 rows to albums
2026-05-17 19:32:23,330 - soeSpotify.database - INFO - Loading 101144 rows to tracks
2026-05-17 19:33:26,364 - soeSpotify.database - INFO - Loaded 101144 rows to tracks
2026-05-17 19:33:26,365 - soeSpotify.database - INFO - Loading 87202 rows to genres
2026-05-17 19:33:32,531 - soeSpotify.database - INFO - Loaded 87202 rows to genres
2026-05-17 19:33:32,533 - soeSpotify.database - INFO - Loading 101144 rows to track_features
2026-05-17 19:34:11,875 - soeSpotify.database - INFO - Loaded 101144 rows to track_features
2026-05-17 19:34:11,876 - soeSpotify.database - INFO - Database sync completed successfully
2026-05-17 19:34:11,877 - __main__ - INFO - Database sync completed in 128.1 seconds

## Verify Database Views

Query the created SQL views to verify data was loaded correctly.

In [18]:
from sqlalchemy import create_engine, text

engine = create_engine(config.DATABASE_URL, echo=False, future=True)

# Test queries
queries = [
    ('Total Artists', 'SELECT COUNT(*) as count FROM home.artists'),
    ('Total Tracks', 'SELECT COUNT(*) as count FROM home.tracks'),
    ('Total Albums', 'SELECT COUNT(*) as count FROM home.albums'),
    ('Total Genres', 'SELECT COUNT(*) as count FROM home.genres'),
    ('Total Features', 'SELECT COUNT(*) as count FROM home.track_features'),
]

with engine.connect() as conn:
    for name, query in queries:
        result = conn.execute(text(query)).fetchone()
        print(f'{name}: {result[0]:,}')

Total Artists: 56,129
Total Tracks: 101,144
Total Albums: 74,991
Total Genres: 87,202
Total Features: 101,144

In [15]:
# Show top artists by popularity
with engine.connect() as conn:
    query = text('''
        SELECT artist_name, followers, artist_popularity
        FROM home.v_1_2_artists_popularity
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

     artist_name  followers  artist_popularity
0  Ariana Grande   26309771                100
1          Drake   34680740                 98
2    Post Malone   12150628                 96
3     Juice WRLD    3607186                 95
4   XXXTENTACION   11564320                 95
5          Ozuna   15389549                 95
6         Khalid    5476601                 95
7       Anuel Aa    5103877                 94
8          Queen   14130233                 94
9   Travis Scott    5097861                 94

In [16]:
# Show top tracks by features (high energy, danceability, valence)
with engine.connect() as conn:
    query = text('''
        SELECT 
            track_name,
            artist_name,
            danceability,
            energy,
            valence,
            tempo
        FROM home.v_3_1_track_features_full
        WHERE energy > 0.7 AND danceability > 0.6
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

,track_name,artist_name,danceability,energy,valence,tempo
0,Teeje Week,Jordan Sandhu,0.679,0.770,0.839,161.721
1,El Yeyo,Vicente Garcia,0.838,0.703,0.658,104.982
2,Supa Nova,Green Assassin Dollar,0.642,0.712,0.647,83.897
3,Acabaste con mi vida,Franco Argüelles,0.771,0.789,0.771,84.974
4,Fever,YOSA & TAAR,0.662,0.838,0.496,129.884
5,Cada Dia,Tercer Cielo,0.753,0.786,0.867,92.066
6,We Are What We Are (feat. Billy Bros Orchestra...,Bart & Baker,0.843,0.736,0.660,125.012
7,Acceptable in the 80's,Calvin Harris,0.787,0.808,0.942,127.990
8,A.S.S - Original Mix,Future Class,0.814,0.714,0.252,125.005
9,Chances - Mark Ralph Remix,Backstreet Boys,0.689,0.859,0.490,110.022

In [17]:
# Show artist-album relationships
with engine.connect() as conn:
    query = text('''
        SELECT 
            artist_name,
            album_name,
            release_date,
            total_tracks
        FROM home.v_1_5_artist_albums
        WHERE artist_followers > 1000000
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

,artist_name,album_name,release_date,total_tracks
0,Alicia Keys,If I Ain't Got You EP,2019-02-08,6
1,Ludwig van Beethoven,Beethoven: 6 Bagatelles & Piano Sonatas Nos. 3...,2019-03-01,11
2,Ludwig van Beethoven,Beethoven: Piano Concerto No. 2 & Triple Conce...,2019-03-01,7
3,Frédéric Chopin,Chopin: Concertos Nos. 1 & 2,2019-02-22,7
4,Busta Rhymes,The Coming,1996,13
5,Galantis,Bones (feat. OneRepublic) [Steff da Campo Remix],2019-03-01,2
6,R3HAB,Radio Silence (Sem Vox Remix),2019-02-22,1
7,Blur,The Best Of,2000-10-23,28
8,Lil Pump,Drug Addicts,2018-07-06,1
9,Lil Uzi Vert,Go Off,2017-03-02,1

## Summary

All pipeline stages completed successfully:

- ✓ **Raw Stage**: CSV → Parquet (minimal transformation)
- ✓ **Processed Stage**: Data validation and cleaning
- ✓ **Analytics Stage**: Denormalization and feature engineering
- ✓ **Database Sync**: PostgreSQL tables and SQL views created

The data is now ready for analysis and ML model training.