# ETL Pipeline Execution: Spotify Data Processing

This notebook demonstrates the complete data pipeline:
1. **Raw Stage**: Load CSV files and convert to Parquet
2. **Processed Stage**: Clean, validate, and deduplicate data
3. **Analytics Stage**: Denormalize and engineer features for analysis
4. **Database Sync**: Load to PostgreSQL using migration-based schema creation to preserve PK/FK relations and analytical views.

## Setup

In [1]:
import sys
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

import pandas as pd
import pyarrow.parquet as pq

# Add project to path
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Load environment variables (force override if already set in kernel)
load_dotenv(project_root / '.env', override=True)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import pipeline stages
from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage
from soeSpotify.database import DatabaseLoader
from soeSpotify import config

logger.info('Pipeline modules imported successfully')

2026-05-17 18:58:29,532 - __main__ - INFO - Pipeline modules imported successfully

In [2]:
import importlib
import sys

logger.info('Performing deep module reload to pick up code changes...')

# Remove modules from cache to force reimport
modules_to_reload = [
    'soeSpotify.stages.analytics',
    'soeSpotify.stages.processed', 
    'soeSpotify.stages.raw',
    'soeSpotify.database',
    'soeSpotify.config'
]

for mod in modules_to_reload:
    if mod in sys.modules:
        del sys.modules[mod]

# Now import fresh
from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage
from soeSpotify.database import DatabaseLoader

logger.info('Modules reloaded with latest code changes')

2026-05-17 18:58:29,567 - __main__ - INFO - Performing deep module reload to pick up code changes...

2026-05-17 18:58:29,572 - __main__ - INFO - Modules reloaded with latest code changes

## Stage 1: Raw Data Processing

Load CSV files and convert to Parquet for efficient storage and retrieval.

In [3]:
import shutil

logger.info('Clearing all processed and analytics data to start fresh...')
shutil.rmtree(config.DATA_PROCESSED, ignore_errors=True)
shutil.rmtree(config.DATA_ANALYTICS, ignore_errors=True)
logger.info('Old processed/analytics data cleared')

# Deep reload updated modules
import sys
for mod in ['soeSpotify.stages.processed', 'soeSpotify.stages.analytics', 
            'soeSpotify.stages.raw']:
    if mod in sys.modules:
        del sys.modules[mod]

from soeSpotify.stages.raw import RawStage
from soeSpotify.stages.processed import ProcessedStage
from soeSpotify.stages.analytics import AnalyticsStage

logger.info('Updated modules reloaded - ready for fresh pipeline run')

2026-05-17 18:58:29,583 - __main__ - INFO - Clearing all processed and analytics data to start fresh...

2026-05-17 18:58:29,615 - __main__ - INFO - Old processed/analytics data cleared

2026-05-17 18:58:29,620 - __main__ - INFO - Updated modules reloaded - ready for fresh pipeline run

In [4]:
logger.info('Starting Raw Stage...')
start_time = datetime.now()

raw = RawStage()
raw.run()

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Raw Stage completed in {elapsed:.1f} seconds')

2026-05-17 18:58:29,629 - __main__ - INFO - Starting Raw Stage...

2026-05-17 18:58:29,632 - soeSpotify.stages.raw - INFO - Raw parquet directory ready: D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet

2026-05-17 18:58:29,633 - soeSpotify.stages.raw - INFO - ============================================================

2026-05-17 18:58:29,634 - soeSpotify.stages.raw - INFO - RAW STAGE: Loading CSV files → Raw Parquet

2026-05-17 18:58:29,636 - soeSpotify.stages.raw - INFO - ============================================================

2026-05-17 18:58:29,638 - soeSpotify.stages.raw - INFO - Loading tracks from D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_tracks.csv

2026-05-17 18:58:34,536 - soeSpotify.stages.raw - INFO - Loaded 101939 tracks

2026-05-17 18:58:34,537 - soeSpotify.stages.raw - INFO - Saving to D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_tracks.parquet

2026-05-17 18:58:35,266 - soeSpotify.stages.raw - INFO - Saved 101939 tracks to raw stage

2026-05-17 18:58:35,267 - soeSpotify.stages.raw - INFO - Loading artists from D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_artists.csv

2026-05-17 18:58:35,429 - soeSpotify.stages.raw - INFO - Loaded 56129 artists

2026-05-17 18:58:35,430 - soeSpotify.stages.raw - INFO - Saving to D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_artists.parquet

2026-05-17 18:58:35,490 - soeSpotify.stages.raw - INFO - Saved 56129 artists to raw stage

2026-05-17 18:58:35,491 - soeSpotify.stages.raw - INFO - Loading albums from D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Data Sources\spotify_albums.csv

2026-05-17 18:58:36,253 - soeSpotify.stages.raw - INFO - Loaded 75511 albums

2026-05-17 18:58:36,254 - soeSpotify.stages.raw - INFO - Saving to D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_albums.parquet

2026-05-17 18:58:36,428 - soeSpotify.stages.raw - INFO - Saved 75511 albums to raw stage

2026-05-17 18:58:36,429 - soeSpotify.stages.raw - INFO - Loading audio features from D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Features Extracted\low_level_audio_features.csv

2026-05-17 18:58:40,394 - soeSpotify.stages.raw - INFO - Loaded 101909 audio feature records

2026-05-17 18:58:40,396 - soeSpotify.stages.raw - INFO - Saving to D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_audio_features.parquet

2026-05-17 18:58:42,589 - soeSpotify.stages.raw - INFO - Saved 101909 audio features to raw stage

2026-05-17 18:58:42,590 - soeSpotify.stages.raw - INFO - Loading lyrics features from D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\SpotGenTrack\Features Extracted\lyrics_features.csv

2026-05-17 18:58:42,680 - soeSpotify.stages.raw - INFO - Loaded 94954 lyrics feature records

2026-05-17 18:58:42,681 - soeSpotify.stages.raw - INFO - Saving to D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\raw\parquet\raw_lyrics_features.parquet

2026-05-17 18:58:42,729 - soeSpotify.stages.raw - INFO - Saved 94954 lyrics features to raw stage

2026-05-17 18:58:42,730 - soeSpotify.stages.raw - INFO - Raw stage completed successfully

2026-05-17 18:58:42,764 - __main__ - INFO - Raw Stage completed in 13.1 seconds

In [5]:
# Verify raw parquet files were created
raw_files = [
    ('Tracks', config.RAW_TRACKS),
    ('Artists', config.RAW_ARTISTS),
    ('Albums', config.RAW_ALBUMS),
    ('Audio Features', config.RAW_AUDIO_FEATURES),
    ('Lyrics Features', config.RAW_LYRICS_FEATURES),
]

for name, path in raw_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 32 columns
✓ Artists: 56129 rows, 9 columns
✓ Albums: 75511 rows, 16 columns

✓ Audio Features: 101909 rows, 209 columns
✓ Lyrics Features: 94954 rows, 8 columns

## Stage 2: Processed Data

Clean, validate, and deduplicate data. Combine audio and lyrics features.

In [6]:
logger.info('Starting Processed Stage...')
start_time = datetime.now()

# Load raw parquet files
df_raw_tracks = pd.read_parquet(config.RAW_TRACKS)
df_raw_artists = pd.read_parquet(config.RAW_ARTISTS)
df_raw_albums = pd.read_parquet(config.RAW_ALBUMS)
df_raw_audio = pd.read_parquet(config.RAW_AUDIO_FEATURES)
df_raw_lyrics = pd.read_parquet(config.RAW_LYRICS_FEATURES)

processed = ProcessedStage()
processed.run(
    raw_tracks=df_raw_tracks,
    raw_artists=df_raw_artists,
    raw_albums=df_raw_albums,
    raw_audio=df_raw_audio,
    raw_lyrics=df_raw_lyrics,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Processed Stage completed in {elapsed:.1f} seconds')

2026-05-17 18:58:43,563 - __main__ - INFO - Starting Processed Stage...

2026-05-17 18:58:44,462 - soeSpotify.stages.processed - INFO - Processed stage directory ready: D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\processed

2026-05-17 18:58:44,465 - soeSpotify.stages.processed - INFO - ============================================================

2026-05-17 18:58:44,467 - soeSpotify.stages.processed - INFO - PROCESSED STAGE: Cleaning & Validating Data

2026-05-17 18:58:44,469 - soeSpotify.stages.processed - INFO - ============================================================

2026-05-17 18:58:44,471 - soeSpotify.stages.processed - INFO - Processing artists...

2026-05-17 18:58:44,482 - soeSpotify.stages.processed - INFO - Removed null artist_ids, 56129 artists remaining

2026-05-17 18:58:44,503 - soeSpotify.stages.processed - INFO - Removed duplicates, 56129 unique artists

2026-05-17 18:58:44,508 - soeSpotify.stages.processed - INFO - Saving 56129 artists

2026-05-17 18:58:44,644 - soeSpotify.stages.processed - INFO - Processing albums...

2026-05-17 18:58:44,653 - soeSpotify.stages.processed - INFO - Removed null album_ids, 75511 albums remaining

2026-05-17 18:58:44,671 - soeSpotify.stages.processed - INFO - Removed duplicates, 75511 unique albums

2026-05-17 18:58:44,673 - soeSpotify.stages.processed - INFO - Saving 75511 albums

2026-05-17 18:58:44,900 - soeSpotify.stages.processed - INFO - Processing tracks...

2026-05-17 18:58:44,931 - soeSpotify.stages.processed - INFO - Removed null track_ids, 101939 tracks remaining

2026-05-17 18:58:44,953 - soeSpotify.stages.processed - INFO - Removed duplicates, 101939 unique tracks

2026-05-17 18:58:44,965 - soeSpotify.stages.processed - INFO - Saving 101939 tracks

2026-05-17 18:58:45,355 - soeSpotify.stages.processed - INFO - Processing track features...

2026-05-17 18:58:45,585 - soeSpotify.stages.processed - INFO - Combined features for 101909 tracks

2026-05-17 18:58:45,587 - soeSpotify.stages.processed - INFO - Saving 101909 track features

2026-05-17 18:58:48,007 - soeSpotify.stages.processed - INFO - Processed stage completed successfully

2026-05-17 18:58:48,025 - __main__ - INFO - Processed Stage completed in 4.5 seconds

In [7]:
# Verify processed parquet files
processed_files = [
    ('Tracks', config.PROCESSED_TRACKS),
    ('Artists', config.PROCESSED_ARTISTS),
    ('Albums', config.PROCESSED_ALBUMS),
    ('Track Features', config.PROCESSED_TRACK_FEATURES),
]

for name, path in processed_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 26 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 75511 rows, 8 columns
✓ Track Features: 101909 rows, 214 columns

In [8]:
# DEBUG: Check what's actually in processed features before analytics
df_processed_features = pd.read_parquet(config.PROCESSED_TRACK_FEATURES)
print(f"PROCESSED_TRACK_FEATURES columns ({len(df_processed_features.columns)} total):")
print(df_processed_features.columns.tolist()[:20])  # Show first 20
print(f"\nTotal: {len(df_processed_features.columns)} columns")
print(f"\nChecking for audio features:")
for col in ["acousticness", "danceability", "energy", "tempo"]:
    print(f"  {col}: {'YES' if col in df_processed_features.columns else 'NO'}")

PROCESSED_TRACK_FEATURES columns (214 total):
['Chroma_1', 'Chroma_10', 'Chroma_11', 'Chroma_12', 'Chroma_2', 'Chroma_3', 'Chroma_4', 'Chroma_5', 'Chroma_6', 'Chroma_7', 'Chroma_8', 'Chroma_9', 'MEL_1', 'MEL_10', 'MEL_100', 'MEL_101', 'MEL_102', 'MEL_103', 'MEL_104', 'MEL_105']

Total: 214 columns

Checking for audio features:
  acousticness: NO
  danceability: NO
  energy: NO
  tempo: NO

## Stage 3: Analytics Data

Denormalize and create features for analysis and ML. Join artist/album/track relationships.

In [9]:
logger.info('Starting Analytics Stage...')
start_time = datetime.now()

# Load processed parquet files
df_processed_tracks = pd.read_parquet(config.PROCESSED_TRACKS)
df_processed_artists = pd.read_parquet(config.PROCESSED_ARTISTS)
df_processed_albums = pd.read_parquet(config.PROCESSED_ALBUMS)
df_processed_features = pd.read_parquet(config.PROCESSED_TRACK_FEATURES)

analytics = AnalyticsStage()
analytics.run(
    tracks=df_processed_tracks,
    artists=df_processed_artists,
    albums=df_processed_albums,
    features=df_processed_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Analytics Stage completed in {elapsed:.1f} seconds')

2026-05-17 18:58:48,649 - __main__ - INFO - Starting Analytics Stage...

2026-05-17 18:58:49,092 - soeSpotify.stages.analytics - INFO - Analytics stage directory ready: D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\analytics

2026-05-17 18:58:49,094 - soeSpotify.stages.analytics - INFO - ============================================================

2026-05-17 18:58:49,095 - soeSpotify.stages.analytics - INFO - ANALYTICS STAGE: Feature Engineering & Denormalization

2026-05-17 18:58:49,096 - soeSpotify.stages.analytics - INFO - ============================================================

2026-05-17 18:58:49,096 - soeSpotify.stages.analytics - INFO - Building analytics artists table...

2026-05-17 18:58:49,100 - soeSpotify.stages.analytics - INFO - Saving 56129 analytics artists

2026-05-17 18:58:49,167 - soeSpotify.stages.analytics - INFO - Building analytics albums table...

2026-05-17 18:58:49,772 - soeSpotify.stages.analytics - INFO - Filtered albums: 74991/75511 reference valid artists

2026-05-17 18:58:49,830 - soeSpotify.stages.analytics - INFO - Saving 74991 analytics albums

2026-05-17 18:58:49,966 - soeSpotify.stages.analytics - INFO - Building analytics tracks table...

2026-05-17 18:58:51,274 - soeSpotify.stages.analytics - INFO - Filtered tracks: 101939/101939 have valid references

2026-05-17 18:58:51,468 - soeSpotify.stages.analytics - INFO - Saving 101939 analytics tracks

2026-05-17 18:58:51,761 - soeSpotify.stages.analytics - INFO - Building analytics genres table...

2026-05-17 18:58:55,591 - soeSpotify.stages.analytics - INFO - Created 87202 genre mappings

2026-05-17 18:58:55,601 - soeSpotify.stages.analytics - INFO - Saving 87202 analytics genres

2026-05-17 18:58:55,652 - soeSpotify.stages.analytics - INFO - Building analytics track features table...

2026-05-17 18:58:56,471 - soeSpotify.stages.analytics - INFO - Analytics features: 101939 rows, 19 columns

2026-05-17 18:58:56,474 - soeSpotify.stages.analytics - INFO - Saving 101939 feature records

2026-05-17 18:58:56,598 - soeSpotify.stages.analytics - INFO - Analytics stage completed successfully

2026-05-17 18:58:56,602 - __main__ - INFO - Analytics Stage completed in 8.0 seconds

In [10]:
# Verify analytics parquet files
analytics_files = [
    ('Tracks', config.ANALYTICS_TRACKS),
    ('Artists', config.ANALYTICS_ARTISTS),
    ('Albums', config.ANALYTICS_ALBUMS),
    ('Genres', config.ANALYTICS_GENRES),
    ('Track Features', config.ANALYTICS_TRACK_FEATURES),
]

for name, path in analytics_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

✓ Tracks: 101939 rows, 33 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 74991 rows, 10 columns
✓ Genres: 87202 rows, 3 columns
✓ Track Features: 101939 rows, 19 columns

In [11]:
import shutil

logger.info('Clearing old analytics data due to feature extraction fix...')
if config.DATA_ANALYTICS.exists():
    shutil.rmtree(config.DATA_ANALYTICS)
    logger.info('Old analytics directory removed')

logger.info('Re-running Analytics Stage with all audio features...')
start_time = datetime.now()

analytics = AnalyticsStage()
analytics.run(
    tracks=df_processed_tracks,
    artists=df_processed_artists,
    albums=df_processed_albums,
    features=df_processed_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Analytics Stage completed in {elapsed:.1f} seconds')

# Verify updated analytics parquet files (should now have more columns)
analytics_files = [
    ('Tracks', config.ANALYTICS_TRACKS),
    ('Artists', config.ANALYTICS_ARTISTS),
    ('Albums', config.ANALYTICS_ALBUMS),
    ('Genres', config.ANALYTICS_GENRES),
    ('Track Features', config.ANALYTICS_TRACK_FEATURES),
]

print('\nUpdated Analytics Files:')
for name, path in analytics_files:
    if path.exists():
        table = pq.read_table(path)
        print(f'✓ {name}: {len(table)} rows, {table.num_columns} columns')
    else:
        print(f'✗ {name}: NOT FOUND')

2026-05-17 18:58:56,891 - __main__ - INFO - Clearing old analytics data due to feature extraction fix...

2026-05-17 18:58:56,902 - __main__ - INFO - Old analytics directory removed

2026-05-17 18:58:56,903 - __main__ - INFO - Re-running Analytics Stage with all audio features...

2026-05-17 18:58:56,905 - soeSpotify.stages.analytics - INFO - Analytics stage directory ready: D:\Documents\00-Personal\01-FHTW\SS2026\MAD-BB-2-SS2026-SOE-Py\soe-spotify\data\analytics

2026-05-17 18:58:56,906 - soeSpotify.stages.analytics - INFO - ============================================================

2026-05-17 18:58:56,906 - soeSpotify.stages.analytics - INFO - ANALYTICS STAGE: Feature Engineering & Denormalization

2026-05-17 18:58:56,908 - soeSpotify.stages.analytics - INFO - ============================================================

2026-05-17 18:58:56,908 - soeSpotify.stages.analytics - INFO - Building analytics artists table...

2026-05-17 18:58:56,913 - soeSpotify.stages.analytics - INFO - Saving 56129 analytics artists

2026-05-17 18:58:57,023 - soeSpotify.stages.analytics - INFO - Building analytics albums table...

2026-05-17 18:58:57,954 - soeSpotify.stages.analytics - INFO - Filtered albums: 74991/75511 reference valid artists

2026-05-17 18:58:57,999 - soeSpotify.stages.analytics - INFO - Saving 74991 analytics albums

2026-05-17 18:58:58,126 - soeSpotify.stages.analytics - INFO - Building analytics tracks table...

2026-05-17 18:58:59,326 - soeSpotify.stages.analytics - INFO - Filtered tracks: 0/101939 have valid references

2026-05-17 18:58:59,342 - soeSpotify.stages.analytics - INFO - Saving 0 analytics tracks

2026-05-17 18:58:59,355 - soeSpotify.stages.analytics - INFO - Building analytics genres table...

2026-05-17 18:59:04,289 - soeSpotify.stages.analytics - INFO - Created 87202 genre mappings

2026-05-17 18:59:04,302 - soeSpotify.stages.analytics - INFO - Saving 87202 analytics genres

2026-05-17 18:59:04,361 - soeSpotify.stages.analytics - INFO - Building analytics track features table...

2026-05-17 18:59:04,383 - soeSpotify.stages.analytics - INFO - Analytics features: 0 rows, 19 columns

2026-05-17 18:59:04,385 - soeSpotify.stages.analytics - INFO - Saving 0 feature records

2026-05-17 18:59:04,396 - soeSpotify.stages.analytics - INFO - Analytics stage completed successfully

2026-05-17 18:59:04,397 - __main__ - INFO - Analytics Stage completed in 7.5 seconds

Updated Analytics Files:
✓ Tracks: 0 rows, 33 columns
✓ Artists: 56129 rows, 6 columns
✓ Albums: 74991 rows, 10 columns
✓ Genres: 87202 rows, 3 columns
✓ Track Features: 0 rows, 19 columns

## Stage 4: Database Sync

Load analytics DataFrames to PostgreSQL. This stage now uses a **migration-aligned workflow**:
1. **Schema Initialization**: Ensures the `home` schema and all tables exist with proper constraints (PKs/FKs).
2. **Data Refresh**: Truncates existing data while keeping table structures intact.
3. **Safe Loading**: Appends fresh data to the pre-defined schema.

In [12]:
# Load analytics dataframes
logger.info('Loading analytics dataframes...')

df_artists = pd.read_parquet(config.ANALYTICS_ARTISTS)
df_albums = pd.read_parquet(config.ANALYTICS_ALBUMS)
df_tracks = pd.read_parquet(config.ANALYTICS_TRACKS)
df_genres = pd.read_parquet(config.ANALYTICS_GENRES)
df_features = pd.read_parquet(config.ANALYTICS_TRACK_FEATURES)

logger.info(f'Artists: {len(df_artists)} rows')
logger.info(f'Albums: {len(df_albums)} rows')
logger.info(f'Tracks: {len(df_tracks)} rows')
logger.info(f'Genres: {len(df_genres)} rows')
logger.info(f'Features: {len(df_features)} rows')

2026-05-17 18:59:04,522 - __main__ - INFO - Loading analytics dataframes...

2026-05-17 18:59:04,627 - __main__ - INFO - Artists: 56129 rows

2026-05-17 18:59:04,628 - __main__ - INFO - Albums: 74991 rows

2026-05-17 18:59:04,630 - __main__ - INFO - Tracks: 0 rows

2026-05-17 18:59:04,631 - __main__ - INFO - Genres: 87202 rows

2026-05-17 18:59:04,632 - __main__ - INFO - Features: 0 rows

In [13]:
# Sync to PostgreSQL
logger.info(f'Database URL: {config.DATABASE_URL}')
start_time = datetime.now()

db = DatabaseLoader(database_url=config.DATABASE_URL)
db.run(
    artists=df_artists,
    albums=df_albums,
    tracks=df_tracks,
    genres=df_genres,
    features=df_features,
)

elapsed = (datetime.now() - start_time).total_seconds()
logger.info(f'Database sync completed in {elapsed:.1f} seconds')

2026-05-17 18:59:04,646 - __main__ - INFO - Database URL: postgresql://postgres:admin@localhost:5432/soe_spotify

2026-05-17 18:59:04,692 - soeSpotify.database - INFO - Database connection established

2026-05-17 18:59:04,693 - soeSpotify.database - INFO - ============================================================

2026-05-17 18:59:04,694 - soeSpotify.database - INFO - DATABASE SYNC: Loading Analytics → PostgreSQL

2026-05-17 18:59:04,695 - soeSpotify.database - INFO - ============================================================

2026-05-17 18:59:04,696 - soeSpotify.database - INFO - Dropping existing tables for schema parity...

2026-05-17 18:59:04,806 - soeSpotify.database - INFO - Tables dropped

2026-05-17 18:59:04,808 - soeSpotify.database - INFO - Creating schema 'home'...

2026-05-17 18:59:04,812 - soeSpotify.database - INFO - Schema 'home' ready

2026-05-17 18:59:04,813 - soeSpotify.database - INFO - Creating tables if missing...

2026-05-17 18:59:04,879 - soeSpotify.database - INFO - Tables checked/created

2026-05-17 18:59:04,880 - soeSpotify.database - INFO - Creating base views...

2026-05-17 18:59:04,898 - soeSpotify.database - INFO - Base views created

2026-05-17 18:59:04,900 - soeSpotify.database - INFO - Creating analysis views...

2026-05-17 18:59:04,915 - soeSpotify.database - INFO - Analysis views created

2026-05-17 18:59:04,917 - soeSpotify.database - INFO - Loading 56129 rows to artists

2026-05-17 18:59:10,910 - soeSpotify.database - INFO - Loaded 56129 rows to artists

2026-05-17 18:59:10,911 - soeSpotify.database - INFO - Loading 74991 rows to albums

2026-05-17 18:59:25,775 - soeSpotify.database - INFO - Loaded 74991 rows to albums

2026-05-17 18:59:25,778 - soeSpotify.database - INFO - Loading 0 rows to tracks

2026-05-17 18:59:25,791 - soeSpotify.database - INFO - Loaded 0 rows to tracks

2026-05-17 18:59:25,793 - soeSpotify.database - INFO - Loading 87202 rows to genres

2026-05-17 18:59:30,811 - soeSpotify.database - INFO - Loaded 87202 rows to genres

2026-05-17 18:59:30,812 - soeSpotify.database - INFO - Loading 0 rows to track_features

2026-05-17 18:59:30,816 - soeSpotify.database - INFO - Loaded 0 rows to track_features

2026-05-17 18:59:30,816 - soeSpotify.database - INFO - Database sync completed successfully

2026-05-17 18:59:30,817 - __main__ - INFO - Database sync completed in 26.2 seconds

## Verify Database Views

Query the created SQL views to verify data was loaded correctly.

In [14]:
from sqlalchemy import create_engine, text

engine = create_engine(config.DATABASE_URL, echo=False, future=True)

# Test queries
queries = [
    ('Total Artists', 'SELECT COUNT(*) as count FROM home.v_1_1_total_artists'),
    ('Total Tracks', 'SELECT COUNT(*) as count FROM home.tracks'),
    ('Total Albums', 'SELECT COUNT(*) as count FROM home.albums'),
    ('Total Genres', 'SELECT COUNT(*) as count FROM home.genres'),
    ('Total Features', 'SELECT COUNT(*) as count FROM home.track_features'),
]

with engine.connect() as conn:
    for name, query in queries:
        result = conn.execute(text(query)).fetchone()
        print(f'{name}: {result[0]:,}')

Total Artists: 1
Total Tracks: 0
Total Albums: 74,991
Total Genres: 87,202
Total Features: 0

In [15]:
# Show top artists by popularity
with engine.connect() as conn:
    query = text('''
        SELECT artist_name, followers, artist_popularity
        FROM home.v_1_2_artists_popularity
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

     artist_name  followers  artist_popularity
0  Ariana Grande   26309771                100
1          Drake   34680740                 98
2    Post Malone   12150628                 96
3     Juice WRLD    3607186                 95
4   XXXTENTACION   11564320                 95
5          Ozuna   15389549                 95
6         Khalid    5476601                 95
7       Anuel Aa    5103877                 94
8          Queen   14130233                 94
9   Travis Scott    5097861                 94

In [16]:
# Show top tracks by features (high energy, danceability, valence)
with engine.connect() as conn:
    query = text('''
        SELECT 
            track_name,
            artist_name,
            danceability,
            energy,
            valence,
            tempo
        FROM home.v_3_1_track_features_full
        WHERE energy > 0.7 AND danceability > 0.6
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

Empty DataFrame
Columns: [track_name, artist_name, danceability, energy, valence, tempo]
Index: []

In [17]:
# Show artist-album relationships
with engine.connect() as conn:
    query = text('''
        SELECT 
            artist_name,
            album_name,
            release_date,
            total_tracks
        FROM home.v_1_5_artist_albums
        WHERE artist_followers > 1000000
        LIMIT 10
    ''')
    result = pd.read_sql(query, conn)
    display(result)

,artist_name,album_name,release_date,total_tracks
0,Alicia Keys,If I Ain't Got You EP,2019-02-08,6
1,Ludwig van Beethoven,Beethoven: 6 Bagatelles & Piano Sonatas Nos. 3...,2019-03-01,11
2,Ludwig van Beethoven,Beethoven: Piano Concerto No. 2 & Triple Conce...,2019-03-01,7
3,Frédéric Chopin,Chopin: Concertos Nos. 1 & 2,2019-02-22,7
4,Busta Rhymes,The Coming,1996,13
5,Galantis,Bones (feat. OneRepublic) [Steff da Campo Remix],2019-03-01,2
6,R3HAB,Radio Silence (Sem Vox Remix),2019-02-22,1
7,Blur,The Best Of,2000-10-23,28
8,Lil Pump,Drug Addicts,2018-07-06,1
9,Lil Uzi Vert,Go Off,2017-03-02,1

## Summary

All pipeline stages completed successfully:

- ✓ **Raw Stage**: CSV → Parquet (minimal transformation)
- ✓ **Processed Stage**: Data validation and cleaning
- ✓ **Analytics Stage**: Denormalization and feature engineering
- ✓ **Database Sync**: PostgreSQL tables and SQL views created

The data is now ready for analysis and ML model training.